### 
### WARNING: All code in this file were generated by ChatGPT!!!
### 

def to_subscript(number):
    """
    Convert a decimal number to its subscript representation.
    
    Parameters:
        number (int, float, or str): The number to convert.
    
    Returns:
        str: A string with each digit (and '-' sign) converted to a subscript.
    """
    # Mapping for digits and the minus sign to their subscript equivalents.
    subscripts = {
        '0': '₀',
        '1': '₁',
        '2': '₂',
        '3': '₃',
        '4': '₄',
        '5': '₅',
        '6': '₆',
        '7': '₇',
        '8': '₈',
        '9': '₉',
        '-': '₋'
    }
    
    # Convert the input to a string to iterate over each character.
    num_str = str(number)
    
    # Replace each character with its subscript equivalent if available.
    return ''.join(subscripts.get(char, char) for char in num_str)
